source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NSDate_Utils_Example' do
  pod "NSDate_Utils", :path => "../"
end

target 'NSDate_Utils_Tests' do
  pod "NSDate_Utils", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
